# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Vitam
logo:             /public/images/VitamEntete.jpg
tagline:          'Programme interministériel archivage numérique'
description:      'Programme interministériel archivage numérique'
url:              http://www.programmevitam.fr
baseurl:          /

author:
  name:           'Jean-Séverin Lair'
  url:            https://fr.linkedin.com/in/jeanseverinlair

paginate:         5

# Custom vars
version:          R4-0.20.x

github:
  repo:           https://github.com/ProgrammeVitam/vitam
  repoext:           https://github.com/ProgrammeVitam/generateur-seda
  
bintray:
  repo:                https://bintray.com/programmevitam
  repomaven:           https://bintray.com/programmevitam/vitam-maven-release
  repodataset:         https://bintray.com/programmevitam/vitam-annexes/tests-dataset/
  repogenseda:         https://bintray.com/programmevitam/vitam-generateur-seda-dist/
  
listmenu: ["presentation", "documentation", "ressources", "demonstrations", "FAQ"]

# Be sure to insert Ressources
include:        ["_sources", "_static", "_images", "_downloads", "_toc.html", "_toc.htm"]

