# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Vitam
logo:             /public/images/VitamEntete.jpg
tagline:          'Programme interministériel archivage numérique'
description:      'Programme interministériel archivage numérique'
url:              http://www.programmevitam.fr
baseurl:          /

author:
  name:           'Jean-Séverin Lair'
  url:            https://fr.linkedin.com/in/jeanseverinlair

paginate:         5

# Custom vars
version:          Bêta-0.11.1

github:
  repo:           https://github.com/ProgrammeVitam/Vitam
  repoext:           https://github.com/ProgrammeVitam/GenerateurSeda
  
bintray:
  repo:           https://bintray.com/programmevitam
  repomaven:           https://bintray.com/programmevitam/vitam-maven-release
  
