# Dependencies
markdown:         kramdown

# Github parameters
github: [metadata]
encoding: UTF-8
kramdown:
   input: GFM
   hard_wrap: false
   math_engine: mathjax
   syntax_highlighter: rouge
future: true
jailed: false
gfm_quirks: paragraph_end
lsi: false
safe: true
highlighter: rouge
gist:
   noscript: false


# Permalinks
permalink:        pretty

# Setup
title:            Vitam
logo:             /public/images/VitamEntete.jpg
tagline:          'Programme interministériel archivage numérique'
description:      'Programme interministériel archivage numérique'
url:              http://www.programmevitam.fr
baseurl:          '/'
future:           true

author:
  name:           'Jean-Séverin Lair'
  url:            https://fr.linkedin.com/in/jeanseverinlair

paginate:         5

# Custom vars
version:          R6-1.0.x

github:
  repo:           https://github.com/ProgrammeVitam/vitam
  repoext:           https://github.com/ProgrammeVitam/generateur-seda

bintray:
  repo:                https://bintray.com/programmevitam
  repomaven:           https://bintray.com/programmevitam/vitam-maven-release
  repodataset:         https://bintray.com/programmevitam/vitam-annexes/tests-dataset/
  repogenseda:         https://bintray.com/programmevitam/vitam-generateur-seda-dist/

listmenu: ["presentation", "VaS", "documentation", "ressources", "versions", "demonstrations", "FAQ"]

# Be sure to insert Ressources
include:        ["_sources", "_static", "_images", "_downloads", "_toc"]
